name: Publish PHP SDK

on:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          php-version: '8.3'
      - run: composer install --prefer-dist --no-progress
      - run: make release
