name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.4']

    container:
      image: php:${{ matrix.php-version }}-cli

    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y unzip
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer install --prefer-dist --no-progress
      - run: make test
